# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('initiative_type', models.CharField(blank=True, help_text='Type of fix (e.g., quick_win, process_change, training, tool_implementation)', max_length=50)),
                ('estimated_effort', models.CharField(blank=True, help_text='Estimated effort (e.g., small, medium, large)', max_length=50)),
                ('estimated_impact', models.CharField(blank=True, help_text='Expected impact (e.g., low, medium, high)', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_channel', models.CharField(blank=True, help_text='Where this issue was identified (e.g., Google Reviews, Instagram, Email)', max_length=100)),
                ('feedback_count', models.PositiveIntegerField(default=1, help_text='Number of feedback items mentioning this issue')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('emotional_intensity', models.PositiveSmallIntegerField(default=5, help_text='Emotional intensity score (1-10)')),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'category'], name='paths_issue_organiz_192844_idx'), models.Index(fields=['priority'], name='paths_issue_priorit_a55566_idx')],
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Custom title for this path', max_length=255)),
                ('goal_statement', models.TextField(blank=True, help_text="e.g., 'My path to success will improve customer satisfaction to increase growth and revenue'")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('baseline_metric', models.JSONField(blank=True, help_text='Baseline measurements before starting', null=True)),
                ('current_metric', models.JSONField(blank=True, help_text='Current measurements for comparison', null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('owner_id', models.UUIDField(blank=True, help_text='User who owns this path', null=True)),
                ('notes', models.TextField(blank=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='paths.initiative')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='paths.issue')),
            ],
            options={
                'verbose_name_plural': 'Paths',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PathComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_id', models.UUIDField(help_text='User who wrote the comment')),
                ('content', models.TextField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='paths.path')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Whether this was suggested by AI')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True)),
                ('cause_category', models.CharField(blank=True, help_text='Category in root cause analysis (e.g., People, Process, Tools, Environment)', max_length=50)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='paths.issue')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='path',
            name='root_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paths', to='paths.rootcause'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='root_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='paths.rootcause'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20)),
                ('assignee_id', models.UUIDField(blank=True, help_text='User assigned to this task', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='paths.task')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='paths.path')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='path',
            index=models.Index(fields=['organization_id', 'status'], name='paths_path_organiz_e53614_idx'),
        ),
        migrations.AddIndex(
            model_name='path',
            index=models.Index(fields=['owner_id'], name='paths_path_owner_i_ce0a07_idx'),
        ),
        migrations.AddIndex(
            model_name='path',
            index=models.Index(fields=['status', 'priority'], name='paths_path_status_dd4c85_idx'),
        ),
    ]
