# Generated by Django 6.0.1 on 2026-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='completed_issues_faced',
            field=models.JSONField(blank=True, help_text='List of issues faced during completion', null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in days', null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='key_learnings',
            field=models.JSONField(blank=True, help_text='Key learnings and insights from this path', null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='on_hold_issues_faced',
            field=models.TextField(blank=True, help_text='Issues faced while working on this path'),
        ),
        migrations.AddField(
            model_name='path',
            name='on_hold_reason',
            field=models.TextField(blank=True, help_text='Why this path is on hold'),
        ),
        migrations.AddField(
            model_name='path',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='project_summary',
            field=models.TextField(blank=True, help_text='High-level summary of the path'),
        ),
        migrations.AddField(
            model_name='path',
            name='team_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of team members'),
        ),
        migrations.AddField(
            model_name='path',
            name='what_was_solved',
            field=models.JSONField(blank=True, help_text='List of things that were solved', null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='what_was_started',
            field=models.TextField(blank=True, help_text='What you started to solve'),
        ),
    ]
