# Generated by Django 6.0.1 on 2026-01-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_path_completed_issues_faced_path_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phase',
            name='assignee_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='phase',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='assignee_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='step',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
