# Generated by Django 6.0.1 on 2026-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0003_actionitem_assignee_name_phase_assignee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='category',
            field=models.CharField(blank=True, help_text='Category like Process, Technical, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='phase',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='phase',
            name='workload_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated days of work', null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='category',
            field=models.CharField(blank=True, help_text='Category like Process, Technical, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='step',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='workload_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated days of work', null=True),
        ),
    ]
